/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mizanposapp.view.innerpanel.keuangan;

import mizanposapp.controller.innerpanel.keuangan.DaftarkaskeluarinputController;
import mizanposapp.helper.Tablestyle;

/**
 *
 * @author Minami
 */
public class Daftarkaskeluar_input_panel extends javax.swing.JPanel {

    /**
     * Creates new form Persedian_inner_panel
     */
    public Daftarkaskeluar_input_panel() {
        initComponents();
        new DaftarkaskeluarinputController(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Supplier = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edpenerima = new javax.swing.JTextField();
        ednoref = new javax.swing.JTextField();
        bcari_penerima = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bsimpan = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bhapus_baris = new javax.swing.JButton();
        ckcetak_faktur = new javax.swing.JCheckBox();
        btambah_baris = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        edtotal_nilai = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lterbilang = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        eddept = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        edketerangan = new javax.swing.JTextField();
        lnocek = new javax.swing.JLabel();
        ltitik2nocek = new javax.swing.JLabel();
        ednocek = new javax.swing.JTextField();
        ltempo = new javax.swing.JLabel();
        ltitik2tempo = new javax.swing.JLabel();
        dtempo = new com.toedter.calendar.JDateChooser();
        bcari_dept = new javax.swing.JButton();
        edakun_giro = new javax.swing.JTextField();
        ltitik2_akun_giro = new javax.swing.JLabel();
        lakun_giro = new javax.swing.JLabel();
        bcariakun_giro = new javax.swing.JButton();
        ckgiro = new javax.swing.JCheckBox();
        dtanggal = new com.toedter.calendar.JDateChooser();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabledata = new Tablestyle(1,new int[]{3});
        jLabel33 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        edakun_kas = new javax.swing.JTextField();
        bcariakun_kas = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel12.setBackground(new java.awt.Color(41, 39, 40));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Input Kas Keluar");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setText("Tanggal");

        Supplier.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Supplier.setText("Penerima");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel5.setText("No. Ref");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel6.setText(":");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel7.setText(":");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel8.setText(":");

        edpenerima.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        edpenerima.setPreferredSize(new java.awt.Dimension(51, 20));
        edpenerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edpenerimaActionPerformed(evt);
            }
        });

        ednoref.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ednoref.setPreferredSize(new java.awt.Dimension(51, 20));
        ednoref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ednorefActionPerformed(evt);
            }
        });

        bcari_penerima.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        bcari_penerima.setText("Cari");
        bcari_penerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcari_penerimaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        bsimpan.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        bsimpan.setText("Simpan");

        bbatal.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        bbatal.setText("Batal");

        bhapus_baris.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        bhapus_baris.setText("Hapus Baris");

        ckcetak_faktur.setBackground(new java.awt.Color(204, 204, 204));
        ckcetak_faktur.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ckcetak_faktur.setText("Cetak Faktur");

        btambah_baris.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btambah_baris.setText("Tambah Baris");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bhapus_baris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btambah_baris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ckcetak_faktur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bbatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bsimpan)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bbatal)
                    .addComponent(bsimpan)
                    .addComponent(bhapus_baris)
                    .addComponent(ckcetak_faktur)
                    .addComponent(btambah_baris))
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel12.setText("Total Nilai");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel13.setText(":");

        edtotal_nilai.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        edtotal_nilai.setPreferredSize(new java.awt.Dimension(51, 20));
        edtotal_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtotal_nilaiActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel15.setText("Terbilang");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel16.setText(":");

        lterbilang.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        lterbilang.setForeground(new java.awt.Color(51, 51, 255));
        lterbilang.setText("Terbilang");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel18.setText("Dept");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel19.setText(":");

        eddept.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        eddept.setPreferredSize(new java.awt.Dimension(51, 20));
        eddept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eddeptActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel20.setText("Ket");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel21.setText(":");

        edketerangan.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        edketerangan.setPreferredSize(new java.awt.Dimension(51, 20));
        edketerangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edketeranganActionPerformed(evt);
            }
        });

        lnocek.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lnocek.setText("No cek");

        ltitik2nocek.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ltitik2nocek.setText(":");

        ednocek.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ednocek.setPreferredSize(new java.awt.Dimension(51, 20));
        ednocek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ednocekActionPerformed(evt);
            }
        });

        ltempo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ltempo.setText("Jatuh Tempo");

        ltitik2tempo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ltitik2tempo.setText(":");

        bcari_dept.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        bcari_dept.setText("Cari");
        bcari_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcari_deptActionPerformed(evt);
            }
        });

        edakun_giro.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        edakun_giro.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        ltitik2_akun_giro.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ltitik2_akun_giro.setText(":");

        lakun_giro.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lakun_giro.setText("Akun Giro");

        bcariakun_giro.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        bcariakun_giro.setText("Cari");
        bcariakun_giro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                bcariakun_giroAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        bcariakun_giro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariakun_giroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lakun_giro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ltitik2_akun_giro))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ltempo)
                        .addGap(18, 18, 18)
                        .addComponent(ltitik2tempo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lnocek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ltitik2nocek))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edketerangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ednocek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dtempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(eddept, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(bcari_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(edakun_giro)
                        .addGap(2, 2, 2)
                        .addComponent(bcariakun_giro))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(eddept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(bcari_dept))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(edketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ltitik2nocek)
                    .addComponent(ednocek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnocek))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edakun_giro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcariakun_giro)
                    .addComponent(lakun_giro)
                    .addComponent(ltitik2_akun_giro))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ltitik2tempo)
                        .addComponent(ltempo))
                    .addComponent(dtempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ckgiro.setBackground(new java.awt.Color(255, 255, 255));
        ckgiro.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ckgiro.setText("Cek / Giro");

        tabledata.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tabledata);

        jLabel33.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel33.setText("Akun Pengeluaran");

        jLabel37.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel37.setText(":");

        edakun_kas.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        edakun_kas.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edakun_kas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edakun_kasActionPerformed(evt);
            }
        });

        bcariakun_kas.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        bcariakun_kas.setText("Cari");
        bcariakun_kas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                bcariakun_kasAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        bcariakun_kas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariakun_kasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel37))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(15, 15, 15))
                                            .addComponent(Supplier, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(75, 75, 75)
                                                .addComponent(jLabel6))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(edakun_kas)
                                            .addComponent(edpenerima, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bcariakun_kas, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(bcari_penerima, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(ednoref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dtanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lterbilang)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(6, 6, 6)
                                        .addComponent(edtotal_nilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(22, 22, 22)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(ckgiro)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckgiro)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel37)
                                    .addComponent(edakun_kas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bcariakun_kas))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(edpenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(bcari_penerima)
                                    .addComponent(Supplier))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(ednoref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel8))
                                    .addComponent(dtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(edtotal_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(lterbilang))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void edpenerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edpenerimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edpenerimaActionPerformed

    private void bcari_penerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcari_penerimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcari_penerimaActionPerformed

    private void ednorefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ednorefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ednorefActionPerformed

    private void edtotal_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtotal_nilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtotal_nilaiActionPerformed

    private void eddeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eddeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eddeptActionPerformed

    private void edketeranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edketeranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edketeranganActionPerformed

    private void ednocekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ednocekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ednocekActionPerformed

    private void bcari_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcari_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcari_deptActionPerformed

    private void bcariakun_kasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_bcariakun_kasAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_bcariakun_kasAncestorAdded

    private void bcariakun_kasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariakun_kasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcariakun_kasActionPerformed

    private void bcariakun_giroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_bcariakun_giroAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_bcariakun_giroAncestorAdded

    private void bcariakun_giroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariakun_giroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcariakun_giroActionPerformed

    private void edakun_kasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edakun_kasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edakun_kasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Supplier;
    public javax.swing.JButton bbatal;
    public javax.swing.JButton bcari_dept;
    public javax.swing.JButton bcari_penerima;
    public javax.swing.JButton bcariakun_giro;
    public javax.swing.JButton bcariakun_kas;
    public javax.swing.JButton bhapus_baris;
    public javax.swing.JButton bsimpan;
    public javax.swing.JButton btambah_baris;
    public javax.swing.JCheckBox ckcetak_faktur;
    public javax.swing.JCheckBox ckgiro;
    public com.toedter.calendar.JDateChooser dtanggal;
    public com.toedter.calendar.JDateChooser dtempo;
    public javax.swing.JTextField edakun_giro;
    public javax.swing.JTextField edakun_kas;
    public javax.swing.JTextField eddept;
    public javax.swing.JTextField edketerangan;
    public javax.swing.JTextField ednocek;
    public javax.swing.JTextField ednoref;
    public javax.swing.JTextField edpenerima;
    public javax.swing.JTextField edtotal_nilai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JLabel lakun_giro;
    public javax.swing.JLabel lnocek;
    public javax.swing.JLabel ltempo;
    public javax.swing.JLabel lterbilang;
    public javax.swing.JLabel ltitik2_akun_giro;
    public javax.swing.JLabel ltitik2nocek;
    public javax.swing.JLabel ltitik2tempo;
    public javax.swing.JTable tabledata;
    // End of variables declaration//GEN-END:variables
}
