/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mizanposapp.view.frameform;

import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import mizanposapp.controller.innerpanel.pengaturan.LoginController;
import mizanposapp.helper.CrudHelper;
import mizanposapp.helper.FuncHelper;
import mizanposapp.helper.Globalsession;
import mizanposapp.helper.Staticvar;
import mizanposapp.view.Mainmenu;
import mizanposapp.view.innerpanel.pengaturan.Login_panel;

/**
 *
 * @author Minami
 */
public class Konfirmasi extends javax.swing.JPanel {

    /**
     * Creates new form Informasi
     */
    public Konfirmasi(String header, String sub, String aksi) {
        initComponents();
        b1.setText(aksi);
        if (aksi.equals("Shutdown")) {
            blain.setVisible(true);
            blain.setText("Log Out");
        } else {
            blain.setVisible(false);
        }
        lheadertext.setText(header);
        taheader.setText(sub);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lheadertext = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taheader = new javax.swing.JTextArea();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        blain = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(335, 226));

        lheadertext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lheadertext.setForeground(new java.awt.Color(51, 51, 51));
        lheadertext.setText("Header Text");

        jPanel28.setBackground(new java.awt.Color(41, 39, 40));
        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel28.setPreferredSize(new java.awt.Dimension(284, 46));

        jLabel91.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(255, 255, 255));
        jLabel91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mizanposapp/icon/ic_lightbulb_outline_white_36dp.png"))); // NOI18N
        jLabel91.setText("Konfirmasi");

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel91)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel91)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        taheader.setEditable(false);
        taheader.setBackground(new java.awt.Color(255, 255, 255));
        taheader.setColumns(20);
        taheader.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        taheader.setForeground(new java.awt.Color(51, 51, 51));
        taheader.setLineWrap(true);
        taheader.setRows(4);
        taheader.setText("Testing");
        taheader.setWrapStyleWord(true);
        taheader.setCaretColor(new java.awt.Color(255, 255, 255));
        taheader.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(taheader);

        b2.setBackground(new java.awt.Color(255, 255, 255));
        b2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b2.setText("Tutup");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b1.setText("Aksi");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        blain.setBackground(new java.awt.Color(255, 255, 255));
        blain.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        blain.setText("lainnya");
        blain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(blain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(lheadertext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lheadertext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2)
                    .addComponent(b1)
                    .addComponent(blain))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        Staticvar.isupdate = false;
        JDialog jd = (JDialog) this.getRootPane().getParent();
        jd.dispose();
    }//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        Staticvar.isupdate = true;
        JDialog jd = (JDialog) this.getRootPane().getParent();
        jd.dispose();
    }//GEN-LAST:event_b1ActionPerformed

    private void blainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blainActionPerformed
        // TODO add your handling code here:
        JDialog jdroot = (JDialog) this.getRootPane().getParent();
        jdroot.dispose();
        LoginController.username = "";
        JDialog jd = new JDialog(new Mainmenu());
        jd.add(new Login_panel());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        jd.setTitle("Login");
        jd.setVisible(true);
        if (Staticvar.isupdate == false) {
            FuncHelper.konfir("Anda ingin mematikan Komputer?", "Jika anda menekan ya maka komputer akan dimatikan ", "Ya");
            if (Staticvar.isupdate == true) {
                Staticvar.isupdate = false;
                System.exit(0);
            }
        } else {
            Staticvar.isupdate = false;
            LoginController.username = "";
            new CrudHelper();
            new Globalsession(Staticvar.id_user_aktif);
        }
    }//GEN-LAST:event_blainActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton b1;
    public javax.swing.JButton b2;
    public javax.swing.JButton blain;
    public javax.swing.JLabel jLabel91;
    public javax.swing.JPanel jPanel28;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lheadertext;
    public javax.swing.JTextArea taheader;
    // End of variables declaration//GEN-END:variables
}
