/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mizanposapp.view;

import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;
import javax.swing.JLabel;
import mizanposapp.controller.PenjualanController;

/**
 *
 * @author Minami
 */
public class Penjualan_panel extends javax.swing.JPanel {

    /**
     * Creates new form Persedian_panel
     */
    public Penjualan_panel() {
        initComponents();
        labelstyle(ldaftarkaryawan);
        labelstyle(lsettingbonuspenjualan);
        labelstyle(lsettingharidiskon);
        labelstyle(lsettingdiskonkelompok);
        new PenjualanController(this);
    }

    private void labelstyle(JLabel label) {
        Font font = label.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        label.setFont(font.deriveFont(attributes));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        ldaftarkaryawan = new javax.swing.JLabel();
        lsettingharidiskon = new javax.swing.JLabel();
        lsettingbonuspenjualan = new javax.swing.JLabel();
        lsettingdiskonkelompok = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        bpiutang = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bfakturpenjualan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        breturpenjualan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bpos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();

        setBackground(new java.awt.Color(22, 22, 22));

        jPanel1.setPreferredSize(new java.awt.Dimension(336, 328));

        jPanel4.setBackground(new java.awt.Color(41, 39, 40));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alur Penjualan Barang");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(41, 39, 40));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        ldaftarkaryawan.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ldaftarkaryawan.setForeground(new java.awt.Color(58, 58, 255));
        ldaftarkaryawan.setText("Daftar Karyawan");

        lsettingharidiskon.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lsettingharidiskon.setForeground(new java.awt.Color(58, 58, 255));
        lsettingharidiskon.setText("Setting Diskon Pertanggal");

        lsettingbonuspenjualan.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lsettingbonuspenjualan.setForeground(new java.awt.Color(58, 58, 255));
        lsettingbonuspenjualan.setText("Setting Bonus Penjualan");

        lsettingdiskonkelompok.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lsettingdiskonkelompok.setForeground(new java.awt.Color(58, 58, 255));
        lsettingdiskonkelompok.setText("Setting Diskon perkelompok");

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bpiutang.setMinimumSize(new java.awt.Dimension(100, 100));
        bpiutang.setPreferredSize(new java.awt.Dimension(100, 100));
        bpiutang.setRequestFocusEnabled(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mizanposapp/icon/piutang.png"))); // NOI18N
        bpiutang.add(jLabel4);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel8.setText("Piutang");
        bpiutang.add(jLabel8);

        jPanel9.add(bpiutang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        bfakturpenjualan.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mizanposapp/icon/sales_invoice.png"))); // NOI18N
        bfakturpenjualan.add(jLabel2);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel6.setText("Faktur Penjualan");
        bfakturpenjualan.add(jLabel6);

        jPanel9.add(bfakturpenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        breturpenjualan.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mizanposapp/icon/sales_return.png"))); // NOI18N
        breturpenjualan.add(jLabel3);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel7.setText("Retur Penjualan");
        breturpenjualan.add(jLabel7);

        jPanel9.add(breturpenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        bpos.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mizanposapp/icon/pos.png"))); // NOI18N
        bpos.add(jLabel5);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel9.setText("Point Of Sales");
        bpos.add(jLabel9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lsettingdiskonkelompok)
                        .addComponent(ldaftarkaryawan)
                        .addComponent(lsettingharidiskon)
                        .addComponent(lsettingbonuspenjualan))
                    .addGap(0, 183, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bpos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(bpos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(ldaftarkaryawan)
                .addGap(2, 2, 2)
                .addComponent(lsettingharidiskon)
                .addGap(2, 2, 2)
                .addComponent(lsettingbonuspenjualan)
                .addGap(2, 2, 2)
                .addComponent(lsettingdiskonkelompok)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel bfakturpenjualan;
    public javax.swing.JPanel bpiutang;
    public javax.swing.JPanel bpos;
    public javax.swing.JPanel breturpenjualan;
    public javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JLabel ldaftarkaryawan;
    public javax.swing.JLabel lsettingbonuspenjualan;
    public javax.swing.JLabel lsettingdiskonkelompok;
    public javax.swing.JLabel lsettingharidiskon;
    // End of variables declaration//GEN-END:variables
}
